// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildIndex(arg1) {
  return window['go']['main']['App']['BuildIndex'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteIndexedPath(arg1) {
  return window['go']['main']['App']['DeleteIndexedPath'](arg1);
}

export function GetExcludePaths() {
  return window['go']['main']['App']['GetExcludePaths']();
}

export function GetFileIcon(arg1) {
  return window['go']['main']['App']['GetFileIcon'](arg1);
}

export function GetIndexStats() {
  return window['go']['main']['App']['GetIndexStats']();
}

export function GetIndexedPaths() {
  return window['go']['main']['App']['GetIndexedPaths']();
}

export function GetPerformanceLog() {
  return window['go']['main']['App']['GetPerformanceLog']();
}

export function HasSudoPassword() {
  return window['go']['main']['App']['HasSudoPassword']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function RebuildIndex(arg1) {
  return window['go']['main']['App']['RebuildIndex'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SearchAdvanced(arg1) {
  return window['go']['main']['App']['SearchAdvanced'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetExcludePaths(arg1) {
  return window['go']['main']['App']['SetExcludePaths'](arg1);
}

export function SetSudoPassword(arg1) {
  return window['go']['main']['App']['SetSudoPassword'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopIndexing() {
  return window['go']['main']['App']['StopIndexing']();
}
