// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildIndex(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteIndexedPath(arg1:string):Promise<void>;

export function GetExcludePaths():Promise<Array<string>>;

export function GetFileIcon(arg1:string):Promise<string>;

export function GetIndexStats():Promise<Record<string, any>>;

export function GetIndexedPaths():Promise<Array<Record<string, any>>>;

export function GetPerformanceLog():Promise<string>;

export function HasSudoPassword():Promise<boolean>;

export function HideWindow():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function RebuildIndex(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:boolean,arg3:number):Promise<Array<main.FileEntry>>;

export function SearchAdvanced(arg1:main.SearchOptions):Promise<Array<main.FileEntry>>;

export function SelectFolder():Promise<string>;

export function SetExcludePaths(arg1:Array<string>):Promise<void>;

export function SetSudoPassword(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StopIndexing():Promise<void>;
